---
- pacman: name=iptables state=installed
  sudo: yes

- template:
    src: iptables.rules
    dest: '{{ iptables_rules_path }}'
    mode: 0700
  sudo: yes
  notify: reload iptables

- service:
    name: iptables
    enabled: yes
    state: started
  sudo: yes
